version: "3.8"

services:
  backend:
    image: registry.git.yitec.net/book-chat/bookchat-backend:latest
    volumes:
      - .env:/usr/app/.env
      - ./firebaseServiceAccount.json:/usr/app/firebaseServiceAccount.json
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
